### ISSUE TITLE
Class defyma\helper\EncryptUrl does not exist

### ISSUE THREAD

**Issue by abuujurayj** [defyma/yii2-encrypt-url#1]
I have installed by using composer `require defyma/yii2-encrypt-url:"dev-master"`  

Then I did some configuration in main.php file (advanced template) as below :- 

        `
        'urlManager' => [
                     'showScriptName' => false,
                     'enablePrettyUrl' => true,
                     //'suffix' => '',
                     'rules' => [
                                [
                                    'class' => 'defyma\helper\EncryptUrl',
                                    'skey' => '<my key>',
                                    'pattern' => '',
                                    'route' => 'site/test'
                                ],...
                         ],`

RESULT : ReflectionException, Class defyma\helper\EncryptUrl does not exist

**Comment by defyma** [comment]
Im sorry, this helper is build for yii2-basic template, I would be happy to open merge request or fork this repo. thanks
